version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # Adjust to the Node.js runtime version of your Lambda functions
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo "Building and zipping all Lambda functions..."

      # Create an output directory for all the zipped files
      - mkdir -p artifacts

      # Process pdf-to-text Lambda
      - echo "Processing pdf-to-text function..."
      - cd lambda-src/pdf-to-text && npm install && zip -rq ../../artifacts/pdf-to-text.zip . && cd ../..

      # Process search-function Lambda
      - echo "Processing search-function function..."
      - cd lambda-src/search-function && npm install && zip -rq ../../artifacts/search-function.zip . && cd ../..

      # Process search-gateway Lambda
      - echo "Processing search-gateway function..."
      - cd lambda-src/search-gateway && npm install && zip -rq ../../artifacts/search-gateway.zip . && cd ../..

      # Process upload-to-search Lambda
      - echo "Processing upload-to-search function..."
      - cd lambda-src/upload-to-search && npm install && zip -rq ../../artifacts/upload-to-search.zip . && cd ../..

  post_build:
    commands:
      - echo "Contents of artifacts folder:"
      - ls -R artifacts
      - echo "Uploading artifacts to s3 bucket search-engine-deployment-artificacts-bucket"
      - aws s3 cp artifacts/ s3://search-engine-deployment-artificacts-bucket/ --recursive
      - aws cloudformation deploy \
        --template-file cloudformation-template.yml \
        --stack-name lambda-deployment-stack \
        --parameter-overrides S3Bucket=search-engine-deployment-artificacts-bucket \
        --capabilities CAPABILITY_NAMED_IAM

artifacts:
  files:
    - "*.zip"

  discard-paths: yes
  base-directory: artifacts