AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for deploying Lambda functions.

Parameters:
  S3Bucket:
    Type: String
    Description: Name of the S3 bucket where Lambda artifacts are stored.

Resources:
  PdfToTextLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: pdf-to-text
      Runtime: nodejs20.x  # Adjust to the runtime version of your Lambda functions
      Handler: index.handler
      Role: arn:aws:iam::417355468534:role/lambda-execution-role  # Replace with your IAM role ARN
      Code:
        S3Bucket: search-engine-deployment-artificacts-bucket
        S3Key: pdf-to-text.zip
      MemorySize: 128
      Timeout: 30

  SearchFunctionLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: search-function
      Runtime: nodejs20.x
      Handler: index.handler
      Role: arn:aws:iam::417355468534:role/lambda-execution-role
      Code:
        S3Bucket: search-engine-deployment-artificacts-bucket
        S3Key: search-function.zip
      MemorySize: 128
      Timeout: 30

  SearchGatewayLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: search-gateway
      Runtime: nodejs20.x
      Handler: index.lambdaHandler
      Role: arn:aws:iam::417355468534:role/lambda-execution-role
      Code:
        S3Bucket: search-engine-deployment-artificacts-bucket
        S3Key: search-gateway.zip
      MemorySize: 128
      Timeout: 30

  UploadToSearchLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: upload-to-search
      Runtime: nodejs20.x
      Handler: index.handler
      Role: arn:aws:iam::417355468534:role/lambda-execution-role
      Code:
        S3Bucket: search-engine-deployment-artificacts-bucket
        S3Key: upload-to-search.zip
      MemorySize: 128
      Timeout: 30