### Query OpenSearch Index
GET https://search-open-search-example-npp3yhhetb5gr5ryzxxx7vxdym.us-east-2.es.amazonaws.com/my_open_search_index/_search?pretty=true
Authorization: Basic bWFzdGVyLXVzZXI6TWFzdGVyLXBhc3N3b3JkLTEyMyE=
Content-Type: application/json

{
  "query": {
    "match_all": {}
  }
}

### Search function
POST https://qkjs0hnwij.execute-api.us-east-2.amazonaws.com/search
Content-Type: application/json

{
  "searchQuery": "example query"
}
